name: ihust
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  url_launcher: ^5.0.2

  equatable: ^1.1.0

  bloc: ^3.0.0

  flutter_bloc: ^3.2.0

  crypto: ^2.0.6

  cached_network_image: ^2.0.0

  shared_preferences: ^0.5.6+2

  flutter_svg: ^0.14.3

  http: ^0.12.0+4

  device_info: ^0.4.1+1

  google_fonts: any

  tripledes: ^2.1.0

  json_annotation: ^3.0.1

  flutter_tableview: ^1.0.1
  firebase_core: ^0.4.0+9
  flutter_local_notifications: ^1.4.4
  firebase_messaging: ^6.0.16
  qr_flutter: ^1.1.1
  barcode_scan: 3.0.1
  youtube_player_flutter: ^7.0.0+6


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.2.5

  built_value: ^7.0.9


flutter:

  uses-material-design: true

  assets:
    - assets/dialog/

